### ISSUE TITLE
Too loose with whitespace and dashes 

### ISSUE THREAD

**Issue by jaceofslades** [gpassarelli/parsley.js-credit-card-validator#3]
"   -   5255000000000019" passes validation.  Will fork and submit a patch.

**Comment by gpassarelli** [comment]
Will be waiting for you PR. Thanks

**Comment by gpassarelli** [comment]
@monkeyinsurgency any updates on the PR?

**Comment by gpassarelli** [comment]
@monkeyinsurgency as its been a long time and you didn't reply with anything. I've made some tests, and I believe this is more another type of validation you should have on your application than on this one.
Because in this case, it will still be a valid credit card, as the validation remove all the spaces and dashes( as mostly people will be using some kind of mask for the input, and when you submit the field to charge the card, you should only get the numbers, so it will still be valid.

As I think this is not and issue, I'll close the issue, but if you have any comments, feel free to open it again.

Thanks
